# Generated by Django 3.2.11 on 2022-07-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='timesatmp',
            new_name='timestamp',
        ),
    ]
