# Generated by Django 3.2.11 on 2022-07-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_rename_timesatmp_products_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='warehouse',
        ),
        migrations.AlterField(
            model_name='products',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
